version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - symfony
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres_user:postgres_password@db:5432/postgres"

  web:
    image: nginx:latest
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./deployment/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - symfony

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
